apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "digital_marketplace.fullname" . }}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: {{ .Values.app.port }}
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ template "digital_marketplace.fullname" . }}
