apiVersion: v1
kind: Secret
metadata:
  name: {{ template "digital-marketplace.fullname" . }}-database-password
  labels: 
{{ include "digital-marketplace.labels" . | indent 4}}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  database-password: {{ .Values.image.app.databasePassword | b64enc | quote }}
