{{- $dbAppPassword := (randAlphaNum 32) | b64enc | quote }}
{{- $dbOwnerPassword := (randAlphaNum 32) | b64enc | quote }}
{{- $secretName := print (include "digital-marketplace.fullname" .) }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if $secret }}
{{- $dbAppPassword = index $secret.data "database-app-password" }}
{{- $dbOwnerPassword = index $secret.data "database-owner-password" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
{{ include "digital-marketplace.labels" . | indent 4}}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  database-name: {{ .Values.db.name | b64enc | quote }}
  database-owner-user: {{ .Values.db.ownerUser | b64enc | quote }}
  database-owner-password: {{ $dbOwnerPassword }}
  database-app-user: {{ .Values.db.appUser | b64enc | quote }}
  database-app-password: {{ $dbAppPassword }}
