---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: Network policies for Digital Marketplace AI services
    tags: "network-policy-${APP_GROUP}-${TAG_NAME}"
  name: "ai-network-policy-${APP_GROUP}-${TAG_NAME}"

objects:
# Allow main app to communicate with AI service
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: "allow-app-to-ai-${APP_GROUP}-${TAG_NAME}"
    labels:
      app-group: "${APP_GROUP}"
      template: "ai-network-policy"
  spec:
    podSelector:
      matchLabels:
        app: "ai-${APP_GROUP}-${TAG_NAME}"
    policyTypes:
    - Ingress
    ingress:
    - from:
      - podSelector:
          matchLabels:
            app: "app-${APP_GROUP}-${TAG_NAME}"
      ports:
      - protocol: TCP
        port: 5000

# Allow AI service to communicate with ChromaDB
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: "allow-ai-to-chroma-${APP_GROUP}-${TAG_NAME}"
    labels:
      app-group: "${APP_GROUP}"
      template: "ai-network-policy"
  spec:
    podSelector:
      matchLabels:
        app: "chroma-${APP_GROUP}-${TAG_NAME}"
    policyTypes:
    - Ingress
    ingress:
    - from:
      - podSelector:
          matchLabels:
            app: "ai-${APP_GROUP}-${TAG_NAME}"
      ports:
      - protocol: TCP
        port: 8000

# Allow external traffic to AI service (optional - for direct access during development)
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: "allow-external-to-ai-${APP_GROUP}-${TAG_NAME}"
    labels:
      app-group: "${APP_GROUP}"
      template: "ai-network-policy"
  spec:
    podSelector:
      matchLabels:
        app: "ai-${APP_GROUP}-${TAG_NAME}"
    policyTypes:
    - Ingress
    ingress:
    - ports:
      - protocol: TCP
        port: 5000

# Allow AI service to access external services (Azure AI, etc.)
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    name: "allow-ai-egress-${APP_GROUP}-${TAG_NAME}"
    labels:
      app-group: "${APP_GROUP}"
      template: "ai-network-policy"
  spec:
    podSelector:
      matchLabels:
        app: "ai-${APP_GROUP}-${TAG_NAME}"
    policyTypes:
    - Egress
    egress:
    # Allow DNS resolution
    - to: []
      ports:
      - protocol: UDP
        port: 53
      - protocol: TCP
        port: 53
    # Allow HTTPS traffic for Azure AI services
    - to: []
      ports:
      - protocol: TCP
        port: 443
    # Allow communication to PostgreSQL database
    - to:
      - podSelector:
          matchLabels:
            cluster-name: "patroni-${APP_GROUP}-${TAG_NAME}"
      ports:
      - protocol: TCP
        port: 5432
    # Allow communication to ChromaDB
    - to:
      - podSelector:
          matchLabels:
            app: "chroma-${APP_GROUP}-${TAG_NAME}"
      ports:
      - protocol: TCP
        port: 8000

parameters:
- name: APP_GROUP
  displayName: App Group
  required: true
  value: digmkt

- name: TAG_NAME
  displayName: Environment tag name.
  required: true
  value: dev
