apiVersion: v2
name: digital-marketplace
description: A Helm chart for the Digital Marketplace
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: spilo
    version: 0.1.0
    repository: https://bcgov.github.io/spilo-chart
    # by default, the object created will be named <your-app>-spilo. You can use an alias to override the -spilo suffix
    # alias: postgres
