name: Create and publish AI service Docker image

on:
  push:
    branches:
      - development
    paths:
      - 'src/marketplace-ai/**'
      - '.github/workflows/publish_ai_image.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build for'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - test
        - prod

env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-ai
  TAG: sha-${{ github.sha }}
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}

jobs:
  build-and-push-ai-image:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push AI service Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./src/marketplace-ai
          file: ./src/marketplace-ai/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # Optional: Add a job to trigger deployment notification or other downstream processes
  notify-build-complete:
    needs: build-and-push-ai-image
    runs-on: ubuntu-22.04
    if: success()
    steps:
      - name: Build completion notification
        run: |
          echo "AI service image built successfully!"
          echo "Image: ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          echo "To deploy to dev environment, run:"
          echo "  ./scripts/deploy-ai-services.sh dev"
